### ISSUE TITLE
Security Plugin doubles up "Required security scopes:" description addition

### ISSUE THREAD

**Issue by douglaswth** [goadesign/plugins#31]
After the addition of OpenAPI YAML generation, the `Required security scopes:` addition to the description is doubled up in both the YAML and JSON output:

```yaml
      description: |-
        Index returns the list of thingies in a thing.

        Required security scopes:
          * `thing:read`

        Required security scopes:
          * `thing:read`
```

```js
"description":"Index returns the list of thingies in a thing.\n\nRequired security scopes:\n  * `thing:read`\n\nRequired security scopes:\n  * `thing:read`"
```
